const mongoose = require('mongoose');

const issueByGeminiSchema = new mongoose.Schema({
    userId: {
        type: String,
        required: true
    },
    // Fields generated by Gemini AI
    title: {
        type: String,
        required: true
    },
    description: {
        type: String,
        required: true
    },
    impact: {
        type: String,
        required: true
    },
    urgency: {
        type: String,
        required: true,
        enum: ['critical', 'high', 'medium', 'low', 'pending'],
        default: 'pending'
    },
    // Timestamps for tracking when the issue was created and updated
}, { timestamps: true });

module.exports = mongoose.model('IssueByGemini', issueByGeminiSchema);